header: Fatih Zor
title: Codey
description: >-
  Software Development Team Lead
repo: https://github.com/FatihZor/codey # site repo [optional]

data-theme: dark # default theme "dark" | "light"

discus-identifier: fatihzor


paginate: 10
paginate_path: "/blog/page:num/"


authors:
  fatih:
    name: Fatih Zor
    bio: Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better.
    userpicture: 
    username: # general username
    github: # github username
    twitter: # twitter username
    email: info@fatihzor.dev # email adress

# URL settings
# url: "https://fatihzor.github.io" # Domain Name of host. [username].github.io for github pages
# baseurl: "/codey" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
# permalink: pretty # For posts, Jekyll also provides the following built-in styles for convenience [pretty] -> /:categories/:year/:month/:day/:title/

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

# local
url: "http://localhost:4000" 
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-toc

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "fatih"
      pinned: false
      toc: false

relative_links:
  enabled:     true
  collections: false

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-

nav:
  items:
    -
      title: Home
      url: /
    -
      title: About
      url: /about
  button:
    title: Fatih Zor
    icon: bi-person
    url: https://fatihzor.dev


settings:
  html_lang: "en"
  pinned_post_icon: "bi-pin-angle-fill"
  post_icon: "bi-file-text-fill"
  search_result_icon: "bi-search"
  pinned_post_date_format: "%d/%m/%Y"
  post_date_format: "%d/%m/%Y"